"""
AUTOGENERATED by git pre-commit hook
"""
git_branch    = "master"
git_shorthash = "9502584"
git_longhash  = "95025844173f832b76193b63944bef36f08c71cf"
git_tag       = "0.9.0.dev"
git_revcount  = ""
