"""
AUTOGENERATED by git post-commit hook. Note that these are always from the PREVIOUS commit, and so may be out of date by one log entry
"""
git_branch    = "master"
git_shorthash = "7fb546f"
git_longhash  = "7fb546fa5312745d270aa878730ef726f6977a76"
git_last_tag  = "0.9.0.dev1"
