"""
AUTOGENERATED by git pre-commit hook
"""
git_branch    = "master"
git_shorthash = "3ef7b56"
git_longhash  = "3ef7b567b580ecd5f04fbafa3923a58feac8ea2f"
git_tag       = "0.9.0.dev"
git_revcount  = ""
